### PR TITLE
Fix erase for enum argument.

### LINKED ISSUE #23: erase implementation
The implementation of `erase` looks to me like it only unsets the corresponding flags if they are already set, but if they are unset, it sets them. So its more like a `toggle`:

https://github.com/grisumbras/enum-flags/blob/25f474d6063c658c7bf18a1dc74d781e1cf233dd/include/flags/flags.hpp#L248-L264

I would expect `erase` to always unset. For that, should it be more like `val &= ~e`, or maybe also `val = (val | e) ^ e;`?

### PR DESCRIPTION
**Pull request by NikolausDemmel**
- Previous implementation was not correct for already unset flag.

Fixes #23

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
Sorry, took a while. I just noticed this again.

Looking at the issue, I think this is the only changed needed.

**Comment by grisumbras** [comment]
Can you please replace it with `val_ &= ~e;`? I checked with several compilers on CE, most give the same result, but ironically ICC gives better codegen in this case.

Also, please add a test that checks for correct erasure.

**Comment by NikolausDemmel** [comment]
Sure. Is there documentation on how to build and run the tests, or could you give me the tl;dr? I'm not so familiar with neither boost build nor conan.

**Comment by NikolausDemmel** [comment]
PS: I'm guessing you wanted `val_ &= ~static_cast<impl_type>(e)`, else it doesn't compile for me (clang/macos).

**Comment by grisumbras** [comment]
If you are willing to use Conan, then the simplest process to run test is this:
```shell
conan remote add grisumbras https://api.bintray.com/conan/grisumbras/conan
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
conan create .
```
(run from the root directory of the project).

If you prefer to not use Conan, then
1. Install Boost.Build (a recent version). You can get it with Boost from https://www.boost.org/users/download/
2. Run `b2 test`  from the root directory of the project.

**Comment by NikolausDemmel** [comment]
Thanks. Conan worked for me. This is sufficient for running the tests.

I updated the PR. I also noticed a wrong return value for erase with iterator range. At least I think it should be like this.

Using boost build directly didn't work for me. I have a recent version from homebrew. Not sure if I missing some setup or config on my end...

```
$ b2 test
warning: No toolsets are configured.
warning: Configuring default toolset "darwin".
warning: If the default is wrong, your build may not work correctly.
warning: Use the "toolset=xxxxx" option to override our guess.
warning: For more configuration options, please consult
warning: http://boost.org/boost-build2/doc/html/bbv2/advanced/configuration.html
error: Unable to find file or target named
error:     '/boost_config//libs'
error: referred to from project at
error:     'test'
error: could not resolve project reference '/boost_config'
```

**Comment by grisumbras** [comment]
Thanks for this patch.

**Pull request merged**
